### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Tpoffdchn** [LearningLimb/learning-limb-website#1]
1. **Main Headline bubble** - Please lighten (Soften), the current color is too bright.  
2. **Navigation Buttons** - When selected we can either change to a different color or put a leaf around it, currently it places an orange box around it.  
3. **Numbers (Choose, Build, Learn)** - Please outline the circle in darker version of color within the box so they stand out better.
4. **Choose, Build, Learn Bubbles** - Will need a button within the bubbles for each step.  
- _Choose button_ - Will go to the "Our Books" section and prompt for logic to view boy or girl books after that follow login or new user logic.
- _Build Button_ - Will prompt user to login.  If logged in will take them through the logic behind choosing book (See choose button).  If logged in will take them to User profile to display started (and saved) projects.
- _Learn Button_ - Will take the user to login, if not logged in.

**Comment by learninglimb-admin** [comment]
Broke this into separate issues. Closing.
