### ISSUE TITLE
It's just too pink

### ISSUE THREAD

**Issue by learninglimb-admin** [LearningLimb/learning-limb-website#2]
I would like the login button and the main bubble’s magenta/florescent pink faded out a bit.  That color is pretty bright.

**Comment by Tpoffdchn** [comment]
The main banner is now red.  We previously changed this because it was too bright.  The pink was fine, it was just too bright and was requested to be changed to lighter, more visually pleasing pink.  

The login button was red and needs to be changed back to red.

**Comment by learninglimb-admin** [comment]
Last commit should have fixed this.
