### ISSUE TITLE
Enhance selected nav button

### ISSUE THREAD

**Issue by learninglimb-admin** [LearningLimb/learning-limb-website#3]
When selected we can either change to a different color or put a leaf around it, currently it places an orange box around it.

**Comment by Tpoffdchn** [comment]
The orange box in Chrome is gone but it's still there in Firefox.  See attached screen grab.
![menu bar](https://cloud.githubusercontent.com/assets/22603946/22607602/8e2031cc-ea26-11e6-8e5a-2d2c13c274fd.png)

**Comment by Tpoffdchn** [comment]
Per @madbytes please remove the leaf and try changing the font on selected buttons to yellow.
