### ISSUE TITLE
Enhance home page steps

### ISSUE THREAD

**Issue by learninglimb-admin** [LearningLimb/learning-limb-website#4]
Please outline the circle in darker version of color within the box so they stand out better.

**Comment by Tpoffdchn** [comment]
The orange box in Chrome is gone but it's still there in Firefox.  See attached screen grab.
![menu bar](https://cloud.githubusercontent.com/assets/22603946/22607602/8e2031cc-ea26-11e6-8e5a-2d2c13c274fd.png)

**Comment by learninglimb-admin** [comment]
Closing per #8
