### ISSUE TITLE
Header Bar

### ISSUE THREAD

**Issue by Tpoffdchn** [LearningLimb/learning-limb-website#6]
Didn't we previously change the header bar to roll with the scroll down and was transparent?  I think that was something you were going to update and roll out after our last "session".

**Comment by Tpoffdchn** [comment]
What's you input on this?

**Comment by learninglimb-admin** [comment]
@Tpoffdchn I'm not sure what you mean, I deployed that work nearly immediately after that. Is it not behaving as expected?

**Comment by learninglimb-admin** [comment]
@Tpoffdchn This caused a lot of side effects to the user experience we didn't consider, especially on mobile. For now the navbar will scroll up with the rest of the page and I will do my best to make the site responsive so users do not have to scroll anyway. If we need to I will refactor the site at a later date and lock the navbar; mind you, that will take some time. Closing.

**Comment by Tpoffdchn** [comment]
Understood, we can look at it later.
