### ISSUE TITLE
Boy / Girl Icon (silhouette)

### ISSUE THREAD

**Issue by Tpoffdchn** [LearningLimb/learning-limb-website#7]
Can we find a better one that is a child boy and child girl?

**Comment by learninglimb-admin** [comment]
@Tpoffdchn I use font-awesome for all of the iconography. We could potentially replace the boy silhouette with this --> http://fontawesome.io/icon/child/

Beyond that I would need a custom image. In the mean time I'll see what images I have and change them.

**Comment by learninglimb-admin** [comment]
Closing since we moved to jumping-boy/girl pictures
