### ISSUE TITLE
General Site and Home Page

### ISSUE THREAD

**Issue by Tpoffdchn** [LearningLimb/learning-limb-website#8]
#- [x] Where did the correct "KBStickToThePlan" font go?  
- [x] Remove numbers from step boxes on home page
- [x] Change colors of red blocks, use pinkish-purple from "Girl" block in place of red color in body blocks
- [x] Add a Limbo graphic to all blocks that are currently red, that are changing to pinkish-purple.  We can decide later which Limbo works the best.
- [x] Revisit header staying scroll locked
  - Will implement later. Currently it creates a number of side effects that create a bad user experience. This will take time to refactor and make responsive.
- [x] Make sure orange in "Support" button matches blocks of orange in body, it seems that one is darker than the other.
- [x] No indication of login failure for wrong username/password.
- [x] ~Forgot password button takes you to signup page~
    - Moved to #18
- [x] Change "Support" to "Contact Us"
- [x] Change "About Us" to "Who is Limbo?"
- [x] ~Add footer for privacy policy, legal disclaimer, refund policy links.  We will be adding more later.~
  - Moved to #22

**Comment by learninglimb-admin** [comment]
@Tpoffdchn @madbytes The "KBStickToThePlan" font is in `src/assets` as [default-font.woff](https://github.com/LearningLimb/learning-limb-website/blob/master/src/assets/default-font.woff) and [default-font.eot](https://github.com/LearningLimb/learning-limb-website/blob/master/src/assets/default-font.eot).

@Tpoffdchn Remember you had me change this to the [Poppins](https://github.com/LearningLimb/learning-limb-website/blob/master/src/scss/main.scss#L1) font face. Please advise if you'd like to change it back.

**Comment by learninglimb-admin** [comment]
@Tpoffdchn @madbytes The orange is the same hex all over. I use Sass variables to ensure consistency ---> https://github.com/LearningLimb/learning-limb-website/blob/master/src/scss/base/_color.scss#L5

**Comment by madbytes** [comment]
Yes, please change the font back.  I don't know why that was a request, but it's a big fail.

**Comment by Tpoffdchn** [comment]
Please see the attached images.  They represent the look of the font on my machine versus my phone and @madbytes machine.  I am unsure why on my computer in both Firefox and Chrome it looks like the "capture" file and on other machines it looks like the image.
![capture](https://cloud.githubusercontent.com/assets/22603946/22755026/773e98da-ee0f-11e6-8647-511e46e7ab52.JPG)
![image](https://cloud.githubusercontent.com/assets/22603946/22755027/7741224e-ee0f-11e6-9380-df21c9e614ad.png)

**Comment by learninglimb-admin** [comment]
@Tpoffdchn I'm going to guess that it's a difference of screens and pixel density. Seems like screens with a high pixel density, like a smart phone, display the font crisp and clear whereas on lower density screens it gets a little blurry. It's just a guess but either way there's nothing I can do to enhance it or make it more crisp.

**Comment by madbytes** [comment]
Any idea why the font looked fine before we removed it and now is blowing out after putting it back?

**Comment by madbytes** [comment]
[KBwithWoff2.zip](https://github.com/LearningLimb/learning-limb-website/files/762418/KBwithWoff2.zip)

**Comment by madbytes** [comment]
[bubble gum sans.zip](https://github.com/LearningLimb/learning-limb-website/files/762459/bubble.gum.sans.zip)

**Comment by madbytes** [comment]
Lets try Bubble Gum Sans instead and see if we get similar edge bleed.

**Comment by Tpoffdchn** [comment]
What is the status on the fonts?  On my screen there is so much blending together it's almost illegible.

**Comment by Tpoffdchn** [comment]
Can we also change the Main Page and other pages (with the exception of the boy and girl books pages) jumbotron to color #CD41CD.  Thank you.

**Comment by Tpoffdchn** [comment]
What do you think?

![main page](https://cloud.githubusercontent.com/assets/22603946/22841585/2cbedb52-efa0-11e6-9764-6b99cc5e66df.jpg)
